# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestEditTask():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_editTask(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(797, 816)
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) a > button").click()
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    
    # Xóa nội dung cũ trước khi nhập mới
    task_field = self.driver.find_element(By.NAME, "task")
    task_field.clear()  # Thêm dòng này để xóa nội dung cũ
    
    # Nhập nội dung mới
    task_field.send_keys("React")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()

